/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dcd9d9',
        'on-tertiary-fixed-variant': '#623b4c',
        'on-secondary-fixed': '#281331',
        'outline-variant': '#d0c5af',
        'secondary-fixed-dim': '#dcbce3',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e4e2e1',
        secondary: '#6f5577',
        surface: '#fcf9f8',
        background: '#fcf9f8',
        primary: { DEFAULT: '#735c00', container: '#d4af37' },
        'on-surface-variant': '#4d4635',
        'surface-container-low': '#f6f3f2',
        'on-error': '#ffffff',
        'on-background': '#1b1c1c',
        tertiary: '#7c5264',
        'inverse-primary': '#e9c349',
        'secondary-container': '#f6d5fd',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#f9d8ff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#241a00',
        'surface-container': '#f0eded',
        'primary-fixed': '#ffe088',
        outline: '#7f7663',
        'surface-bright': '#fcf9f8',
        'inverse-on-surface': '#f3f0f0',
        'on-tertiary-fixed': '#301120',
        'on-primary-container': '#554300',
        'primary-fixed-dim': '#e9c349',
        'on-secondary': '#ffffff',
        'tertiary-container': '#d8a5b9',
        'surface-variant': '#e4e2e1',
        'tertiary-fixed': '#ffd8e6',
        'surface-container-high': '#eae7e7',
        'tertiary-fixed-dim': '#edb8cc',
        'on-secondary-container': '#74597c',
        'on-surface': '#1b1c1c',
        'on-tertiary-container': '#603a4a',
        'inverse-surface': '#303030',
        'surface-tint': '#735c00',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#574500',
        'primary-container': '#d4af37',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#563e5e',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
        accent: ['Dancing Script', 'cursive'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #D4AF37 0%, #3D2645 100%)',
        'gradient-accent': 'linear-gradient(135deg, #E8B4C8 0%, #D4AF37 100%)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
